import { useState } from 'react'
type Props = { open: boolean; onClose: () => void; date: Date | null; startTime: string; endTime: string; roomId?: string; user: { id: string; bands: { id: string; name: string }[] } | null; onCreated: () => void }
const toUtc = (date: Date, time: string) => { const [hours, minutes] = time.slice(0, 5).split(':').map(Number); return new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate(), hours, minutes) - 19_800_000).toISOString() }
export function BookingRequestModal({ open, onClose, date, startTime, endTime, roomId, user, onCreated }: Props) {
  const [bandId, setBandId] = useState(user?.bands[0]?.id ?? ''); const [reason, setReason] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  if (!open || !date || !user) return null
  const submit = async () => { if (!roomId || !bandId) return setMessage('Choose a band before submitting.'); setBusy(true); setMessage(''); const response = await fetch('/api/requests', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ user_id: user.id, band_id: bandId, room_id: roomId, slot_start: toUtc(date, startTime), slot_end: toUtc(date, endTime), reason }) }); const data = await response.json().catch(() => ({})) as { message?: string }; setBusy(false); if (!response.ok) return setMessage(data.message ?? 'Unable to submit request.'); onCreated(); onClose() }
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><div className="auth-modal" role="dialog" aria-modal="true" onMouseDown={event => event.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close">×</button><p className="eyebrow">REQUEST SLOT</p><h2>{date.toLocaleDateString('en-IN', { weekday: 'long', month: 'short', day: 'numeric' })}</h2><p className="modal-time">{startTime} – {endTime}</p><label>Band<select value={bandId} onChange={event => setBandId(event.target.value)}>{user.bands.map(band => <option key={band.id} value={band.id}>{band.name}</option>)}</select></label><label>Reason<textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="Why do you need this slot?" /></label>{message && <p className="form-error">{message}</p>}<button className="form-submit" disabled={busy} onClick={submit}>{busy ? 'Submitting…' : 'Submit request'}</button></div></div>
}
