import { useEffect, useState } from 'react'
type Slot = { id: string; start_time: string; end_time: string; enabled: boolean }
export function DashboardScreen({ admin }: { admin: boolean }) {
  const [slots, setSlots] = useState<Slot[]>([]); const [start, setStart] = useState('09:00'); const [end, setEnd] = useState('10:00'); const [message, setMessage] = useState('')
  const [notificationEmail, setNotificationEmail] = useState(''); const [spreadsheetId, setSpreadsheetId] = useState(''); const [sheetName, setSheetName] = useState(''); const [releaseDay, setReleaseDay] = useState(0); const [releaseTime, setReleaseTime] = useState('13:30')
  const load = () => { if (admin) fetch('/api/slotconfig').then(response => response.ok ? response.json() : []).then(setSlots).catch(() => setMessage('Unable to load slot configuration.')) }
  useEffect(() => { load(); if (admin) fetch('/api/system-settings').then(response => response.ok ? response.json() : null).then((settings: { notification_email?: string; sheets_spreadsheet_id?: string; sheets_sheet_name?: string; booking_release_day?: number; booking_release_time?: string } | null) => { if (settings) { setNotificationEmail(settings.notification_email ?? ''); setSpreadsheetId(settings.sheets_spreadsheet_id ?? ''); setSheetName(settings.sheets_sheet_name ?? ''); setReleaseDay(settings.booking_release_day ?? 0); setReleaseTime(settings.booking_release_time ?? '13:30') } }) }, [admin])
  const add = async () => { const response = await fetch('/api/slotconfig', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ start_time: start, end_time: end }) }); if (!response.ok) setMessage('Unable to add slot.'); else load() }
  const remove = async (id: string) => { const response = await fetch(`/api/slotconfig?id=${id}`, { method: 'DELETE' }); if (!response.ok) setMessage('Unable to delete slot.'); else load() }
  const toggle = async (slot: Slot) => { const response = await fetch('/api/slotconfig', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: slot.id, enabled: !slot.enabled }) }); if (!response.ok) setMessage('Unable to update slot.'); else load() }
  if (!admin) return <section className="coming-soon"><div className="eyebrow">JAMROOM</div><h1>Dashboard</h1><p>This page is available to Jamroom administrators.</p></section>
  const saveSettings = async () => { const response = await fetch('/api/system-settings', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ notification_email: notificationEmail, sheets_spreadsheet_id: spreadsheetId, sheets_sheet_name: sheetName, booking_release_day: releaseDay, booking_release_time: releaseTime }) }); setMessage(response.ok ? 'Settings saved.' : 'Unable to save settings.') }
  const runExport = async () => { const response = await fetch('/api/sheets/weekly', { method: 'POST' }); const result = await response.json().catch(() => ({})) as { status?: string; reason?: string }; setMessage(result.status === 'ok' ? 'Weekly sheet exported.' : result.reason ?? 'Unable to run weekly export.') }
  return <section className="content-page"><div className="eyebrow">JAMROOM · ADMINISTRATION</div><h1>Dashboard</h1><div className="admin-form"><h2>Booking slots</h2><label>Start<input type="time" value={start} onChange={event => setStart(event.target.value)} /></label><label>End<input type="time" value={end} onChange={event => setEnd(event.target.value)} /></label><button className="form-submit" onClick={add}>Add slot</button><div className="data-list">{slots.map(slot => <article key={slot.id}><span>{slot.start_time} – {slot.end_time}</span><div className="inline-actions"><button className="button" onClick={() => toggle(slot)}>{slot.enabled ? 'Disable' : 'Enable'}</button><button className="button button--danger" onClick={() => remove(slot.id)}>Delete</button></div></article>)}</div></div><div className="admin-form"><h2>Notifications & Sheets</h2><label>Notification email<input type="email" value={notificationEmail} onChange={event => setNotificationEmail(event.target.value)} /></label><label>Booking release day<select value={releaseDay} onChange={event => setReleaseDay(Number(event.target.value))}>{['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'].map((day, index) => <option value={index} key={day}>{day}</option>)}</select></label><label>Booking release time<input type="time" value={releaseTime} onChange={event => setReleaseTime(event.target.value)} /></label><label>Spreadsheet ID<input value={spreadsheetId} onChange={event => setSpreadsheetId(event.target.value)} /></label><label>Sheet prefix<input value={sheetName} onChange={event => setSheetName(event.target.value)} /></label><button className="form-submit" onClick={saveSettings}>Save settings</button><button className="button" onClick={runExport}>Run weekly export now</button>{message && <p className="form-error" role="status">{message}</p>}</div></section>
}
