import { useCallback, useEffect, useState } from 'react'
import { api, type Band, type ManagedUser } from '../lib/api'

type UserDraft = { id?: string; name: string; email: string; role: 'user' | 'admin'; bandIds: string[] }
type BandDraft = { id?: string; name: string; colour: string }
const emptyUser = (): UserDraft => ({ name: '', email: '', role: 'user', bandIds: [] })
const emptyBand = (): BandDraft => ({ name: '', colour: '#7c5ce0' })

export function ManagementScreen({ admin }: { admin: boolean }) {
  const [users, setUsers] = useState<ManagedUser[]>([]); const [bands, setBands] = useState<Band[]>([])
  const [userDraft, setUserDraft] = useState<UserDraft | null>(null); const [bandDraft, setBandDraft] = useState<BandDraft | null>(null); const [message, setMessage] = useState('')
  const load = useCallback(async () => { if (!admin) return; try { const [loadedUsers, loadedBands] = await Promise.all([api.users(), api.bands()]); setUsers(loadedUsers); setBands(loadedBands) } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load management data.') } }, [admin])
  useEffect(() => { void load() }, [load])
  if (!admin) return <section className="coming-soon"><div className="eyebrow">JAMROOM</div><h1>Manage people</h1><p>This page is available to Jamroom administrators.</p></section>
  const saveUser = async () => { if (!userDraft) return; try { if (userDraft.id) await api.updateUser(userDraft.id, userDraft); else await api.register(userDraft); setUserDraft(null); setMessage('User saved.'); await load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save user.') } }
  const saveBand = async () => { if (!bandDraft) return; try { if (bandDraft.id) await api.updateBand(bandDraft.id, bandDraft); else await api.createBand(bandDraft); setBandDraft(null); setMessage('Profile saved.'); await load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save profile.') } }
  const toggleBand = (id: string) => setUserDraft(draft => draft ? { ...draft, bandIds: draft.bandIds.includes(id) ? draft.bandIds.filter(value => value !== id) : [...draft.bandIds, id] } : draft)
  return <section className="content-page management-page"><div className="eyebrow">JAMROOM · ADMINISTRATION</div><h1>People & profiles</h1>{message && <p className="form-error" role="status">{message}</p>}<div className="management-grid">
    <section className="admin-panel"><div className="panel-heading"><h2>Users</h2><button className="button button--small" onClick={() => setUserDraft(emptyUser())}>Add user</button></div><div className="responsive-list">{users.map(user => <article key={user.id}><div><b>{user.name}</b><span>{user.email}</span><small>{user.bands.map(band => band.name).join(', ') || 'No profiles'}</small></div><button className="button button--quiet" onClick={() => setUserDraft({ id: user.id, name: user.name, email: user.email, role: user.role, bandIds: user.bands.map(band => band.id) })}>Edit</button></article>)}</div></section>
    <section className="admin-panel"><div className="panel-heading"><h2>Profiles</h2><button className="button button--small" onClick={() => setBandDraft(emptyBand())}>Add profile</button></div><div className="responsive-list">{bands.map(band => <article key={band.id}><div><b><i className="profile-colour" style={{ background: band.colour }} />{band.name}</b><span>{band.colour}</span></div><button className="button button--quiet" onClick={() => setBandDraft(band)}>Edit</button></article>)}</div></section>
  </div>{userDraft && <div className="admin-form form-card"><div className="panel-heading"><h2>{userDraft.id ? 'Edit user' : 'Register user'}</h2><button className="button button--quiet" onClick={() => setUserDraft(null)}>Close</button></div><label>Name<input value={userDraft.name} onChange={event => setUserDraft({ ...userDraft, name: event.target.value })} /></label><label>Email<input type="email" value={userDraft.email} onChange={event => setUserDraft({ ...userDraft, email: event.target.value })} /></label>{userDraft.id && <label>Role<select value={userDraft.role} onChange={event => setUserDraft({ ...userDraft, role: event.target.value as UserDraft['role'] })}><option value="user">User</option><option value="admin">Admin</option></select></label>}<fieldset><legend>Profiles</legend>{bands.map(band => <label className="checkbox-row" key={band.id}><input type="checkbox" checked={userDraft.bandIds.includes(band.id)} onChange={() => toggleBand(band.id)} />{band.name}</label>)}</fieldset><button className="form-submit" onClick={() => void saveUser()}>{userDraft.id ? 'Save user' : 'Register user'}</button>{userDraft.id && <button className="button button--danger" onClick={() => void api.deleteUser(userDraft.id!).then(load).then(() => setUserDraft(null)).catch(error => setMessage(error.message))}>Delete user</button>}</div>}
  {bandDraft && <div className="admin-form form-card"><div className="panel-heading"><h2>{bandDraft.id ? 'Edit profile' : 'Add profile'}</h2><button className="button button--quiet" onClick={() => setBandDraft(null)}>Close</button></div><label>Name<input value={bandDraft.name} onChange={event => setBandDraft({ ...bandDraft, name: event.target.value })} /></label><label>Colour<input type="color" value={bandDraft.colour} onChange={event => setBandDraft({ ...bandDraft, colour: event.target.value })} /></label><button className="form-submit" onClick={() => void saveBand()}>Save profile</button>{bandDraft.id && <button className="button button--danger" onClick={() => void api.deleteBand(bandDraft.id!).then(load).then(() => setBandDraft(null)).catch(error => setMessage(error.message))}>Archive profile</button>}</div>}</section>
}
