import { useEffect, useMemo, useState } from 'react'
type Request = { id: string; status: 'pending' | 'approved' | 'denied'; slot_start: string; slot_end: string; band_name?: string; reason?: string; room_id: string }
export function RequestsScreen({ signedIn, admin }: { signedIn: boolean; admin: boolean }) {
  const [items, setItems] = useState<Request[]>([]); const [message, setMessage] = useState(''); const [filter, setFilter] = useState('all'); const [search, setSearch] = useState(''); const [date, setDate] = useState('')
  const load = () => { if (signedIn) fetch('/api/requests').then(response => response.ok ? response.json() : Promise.reject()).then(setItems).catch(() => setMessage('Unable to load requests.')) }
  useEffect(load, [signedIn])
  const visible = useMemo(() => items.filter(item => (filter === 'all' || item.status === filter) && `${item.band_name} ${item.reason}`.toLowerCase().includes(search.toLowerCase()) && (!date || item.slot_start.startsWith(date))), [items, filter, search, date])
  const action = async (id: string, method: 'DELETE' | 'PUT', status?: string) => { const response = await fetch(`/api/requests?id=${id}`, { method, headers: { 'content-type': 'application/json' }, body: status ? JSON.stringify({ status }) : undefined }); if (!response.ok) setMessage('Unable to update request.'); else load() }
  if (!signedIn) return <section className="coming-soon"><div className="eyebrow">JAMROOM</div><h1>Slot Requests</h1><p>Please sign in to see and manage your booking requests.</p></section>
  return <section className="content-page"><div className="eyebrow">JAMROOM · {admin ? 'ADMINISTRATION' : 'YOUR ACTIVITY'}</div><h1>Slot Requests</h1><div className="request-filters"><input placeholder="Search requests" value={search} onChange={event => setSearch(event.target.value)} /><input type="date" value={date} onChange={event => setDate(event.target.value)} /><select value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="denied">Denied</option></select></div>{message && <p className="form-error">{message}</p>}<div className="data-list">{visible.length ? visible.map(item => <article key={item.id}><div><b>{item.band_name ?? 'Booking request'}</b><span>{new Date(item.slot_start).toLocaleString('en-IN')} – {new Date(item.slot_end).toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' })}</span>{item.reason && <small>{item.reason}</small>}</div><div className="request-actions"><em className={`state state--${item.status}`}>{item.status}</em>{admin && item.status === 'pending' && <><button onClick={() => action(item.id, 'PUT', 'approved')}>Approve</button><button onClick={() => action(item.id, 'PUT', 'denied')}>Deny</button></>}<button onClick={() => action(item.id, 'DELETE')}>Delete</button></div></article>) : <p className="empty">No booking requests yet.</p>}</div></section>
}
