import { and, asc, eq } from 'drizzle-orm'
import { Hono } from 'hono'
import { createBandSchema, slotConfigCreateSchema, slotConfigUpdateSchema, updateBandSchema, updateSystemSettingsSchema, updateUserSchema } from '../schemas.js'
import { getDb, schema } from '../db/client.js'
import { authenticated } from './auth.js'

type Bindings = { DB: D1Database; JWT_SECRET?: string }
const managementRoutes = new Hono<{ Bindings: Bindings }>()
async function admin(c: { env: Bindings; req: { header(name: string): string | undefined } }) { const auth = await authenticated(c); return auth?.user.role === 'ADMIN' && !auth.user.mustChangePassword ? auth : null }
const fail = (c: { json: (body: unknown, status: 401 | 403) => Response }, auth: unknown) => c.json({ error: auth ? 'Forbidden' : 'Unauthorized' }, auth ? 403 : 401)

managementRoutes.get('/users', async c => { const auth = await admin(c); if (!auth) return fail(c, await authenticated(c)); const db = getDb(c.env.DB); const users = await db.select().from(schema.users).orderBy(asc(schema.users.name)); const result = await Promise.all(users.map(async user => ({ id: user.id, name: user.name, email: user.email, role: user.role === 'ADMIN' ? 'admin' : 'user', bands: await db.select({ id: schema.profiles.id, name: schema.profiles.name }).from(schema.userProfiles).innerJoin(schema.profiles, eq(schema.userProfiles.profileId, schema.profiles.id)).where(eq(schema.userProfiles.userId, user.id)) }))); return c.json(result) })
managementRoutes.put('/users', async c => { const auth = await admin(c); if (!auth) return fail(c, await authenticated(c)); const id = c.req.query('id'); const parsed = updateUserSchema.safeParse(await c.req.json().catch(() => ({}))); if (!id || !parsed.success) return c.json({ message: 'Validation failed' }, 400); const db = getDb(c.env.DB); const existing = (await db.select().from(schema.users).where(eq(schema.users.id, id)).limit(1))[0]; if (!existing) return c.json({ message: 'User not found' }, 404); const data = parsed.data; await db.update(schema.users).set({ ...(data.name ? { name: data.name } : {}), ...(data.email ? { email: data.email.toLowerCase() } : {}), ...(data.role ? { role: data.role === 'admin' ? 'ADMIN' : 'USER' } : {}), updatedAt: Date.now() }).where(eq(schema.users.id, id)); if (data.bandIds) { await db.delete(schema.userProfiles).where(eq(schema.userProfiles.userId, id)); if (data.bandIds.length) await db.insert(schema.userProfiles).values(data.bandIds.map(profileId => ({ userId: id, profileId }))) } return c.json({ success: true }) })
managementRoutes.delete('/users', async c => { const auth = await admin(c); if (!auth) return fail(c, await authenticated(c)); const id = c.req.query('id'); if (!id || id === auth.user.id) return c.json({ message: 'Cannot delete this user' }, 400); await getDb(c.env.DB).delete(schema.users).where(eq(schema.users.id, id)); return c.json({ success: true }) })

managementRoutes.post('/bands', async c => { const auth = await admin(c); if (!auth) return fail(c, await authenticated(c)); const parsed = createBandSchema.safeParse(await c.req.json().catch(() => ({}))); if (!parsed.success) return c.json({ message: 'Validation failed' }, 400); const band = { id: crypto.randomUUID(), name: parsed.data.name, color: parsed.data.colour ?? '#4F46E5', active: true, createdAt: Date.now() }; await getDb(c.env.DB).insert(schema.profiles).values(band); return c.json({ id: band.id, name: band.name, colour: band.color }, 201) })
managementRoutes.put('/bands', async c => { const auth = await admin(c); if (!auth) return fail(c, await authenticated(c)); const id = c.req.query('id'); const parsed = updateBandSchema.safeParse(await c.req.json().catch(() => ({}))); if (!id || !parsed.success) return c.json({ message: 'Validation failed' }, 400); const db = getDb(c.env.DB); const found = (await db.select().from(schema.profiles).where(eq(schema.profiles.id, id)).limit(1))[0]; if (!found) return c.json({ message: 'Band not found' }, 404); await db.update(schema.profiles).set({ ...(parsed.data.name ? { name: parsed.data.name } : {}), ...(parsed.data.colour ? { color: parsed.data.colour } : {}) }).where(eq(schema.profiles.id, id)); return c.json({ success: true }) })
managementRoutes.delete('/bands', async c => { const auth = await admin(c); if (!auth) return fail(c, await authenticated(c)); const id = c.req.query('id'); if (!id) return c.json({ message: 'Missing band id' }, 400); await getDb(c.env.DB).update(schema.profiles).set({ active: false }).where(eq(schema.profiles.id, id)); return c.json({ success: true }) })

managementRoutes.post('/slotconfig', async c => { const auth = await admin(c); if (!auth) return fail(c, await authenticated(c)); const parsed = slotConfigCreateSchema.safeParse(await c.req.json().catch(() => ({}))); if (!parsed.success) return c.json({ message: 'Validation failed' }, 400); const db = getDb(c.env.DB); const policy = (await db.select().from(schema.bookingPolicies).where(eq(schema.bookingPolicies.active, true)).limit(1))[0]; if (!policy) return c.json({ message: 'No active booking policy' }, 400); const rows = Array.from({ length: 7 }, (_, dayOfWeek) => ({ id: crypto.randomUUID(), policyId: policy.id, dayOfWeek, startTime: parsed.data.start_time, endTime: parsed.data.end_time, enabled: parsed.data.enabled ?? true })); await db.insert(schema.operatingSchedules).values(rows); return c.json({ id: rows[0].id, start_time: parsed.data.start_time, end_time: parsed.data.end_time, enabled: rows[0].enabled }, 201) })
managementRoutes.put('/slotconfig', async c => { const auth = await admin(c); if (!auth) return fail(c, await authenticated(c)); const parsed = slotConfigUpdateSchema.safeParse(await c.req.json().catch(() => ({}))); if (!parsed.success) return c.json({ message: 'Validation failed' }, 400); const db = getDb(c.env.DB); const source = (await db.select().from(schema.operatingSchedules).where(eq(schema.operatingSchedules.id, parsed.data.id)).limit(1))[0]; if (!source) return c.json({ message: 'Slot config not found' }, 404); await db.update(schema.operatingSchedules).set({ ...(parsed.data.start_time ? { startTime: parsed.data.start_time } : {}), ...(parsed.data.end_time ? { endTime: parsed.data.end_time } : {}), ...(parsed.data.enabled === undefined ? {} : { enabled: parsed.data.enabled }) }).where(and(eq(schema.operatingSchedules.policyId, source.policyId), eq(schema.operatingSchedules.startTime, source.startTime), eq(schema.operatingSchedules.endTime, source.endTime))); return c.json({ success: true }) })
managementRoutes.delete('/slotconfig', async c => { const auth = await admin(c); if (!auth) return fail(c, await authenticated(c)); const id = c.req.query('id'); if (!id) return c.json({ message: 'Missing slot config id' }, 400); const db = getDb(c.env.DB); const source = (await db.select().from(schema.operatingSchedules).where(eq(schema.operatingSchedules.id, id)).limit(1))[0]; if (!source) return c.json({ message: 'Slot config not found' }, 404); await db.delete(schema.operatingSchedules).where(and(eq(schema.operatingSchedules.policyId, source.policyId), eq(schema.operatingSchedules.startTime, source.startTime), eq(schema.operatingSchedules.endTime, source.endTime))); return c.json({ success: true }) })

managementRoutes.get('/system-settings', async c => { const auth = await admin(c); if (!auth) return fail(c, await authenticated(c)); const row = (await getDb(c.env.DB).select().from(schema.systemSettings).limit(1))[0]; if (!row) return c.json({ message: 'System settings not found' }, 404); return c.json({ notification_email: row.notificationEmail, booking_release_day: row.bookingReleaseDay, booking_release_time: row.bookingReleaseTime, sheets_spreadsheet_id: row.sheetsSpreadsheetId, sheets_sheet_name: row.sheetsSheetName }) })
managementRoutes.put('/system-settings', async c => { const auth = await admin(c); if (!auth) return fail(c, await authenticated(c)); const parsed = updateSystemSettingsSchema.safeParse(await c.req.json().catch(() => ({}))); if (!parsed.success) return c.json({ message: 'Validation failed' }, 400); const db = getDb(c.env.DB); const row = (await db.select().from(schema.systemSettings).limit(1))[0]; if (!row) return c.json({ message: 'System settings not found' }, 404); const data = parsed.data; await db.update(schema.systemSettings).set({ ...(data.notification_email !== undefined ? { notificationEmail: data.notification_email || null } : {}), ...(data.booking_release_day !== undefined ? { bookingReleaseDay: data.booking_release_day } : {}), ...(data.booking_release_time ? { bookingReleaseTime: data.booking_release_time } : {}), ...(data.sheets_spreadsheet_id !== undefined ? { sheetsSpreadsheetId: data.sheets_spreadsheet_id || null } : {}), ...(data.sheets_sheet_name !== undefined ? { sheetsSheetName: data.sheets_sheet_name || null } : {}) }).where(eq(schema.systemSettings.id, row.id)); return c.json({ success: true }) })

export { managementRoutes }
