import { SignJWT, importPKCS8 } from 'jose'
import { Hono } from 'hono'
import { getDb, schema } from '../db/client.js'
import { authenticated } from './auth.js'
import { mondayIst, tabName, weeklyGrid } from '../sheets/grid.js'

type Bindings = { DB: D1Database; JWT_SECRET?: string; GOOGLE_SERVICE_ACCOUNT?: string }
type Result = { status: 'ok' | 'skipped' | 'failed'; weekMonday: number; tabName: string | null; rows?: number; cols?: number; reason?: string; error?: string }
const sheetsRoutes = new Hono<{ Bindings: Bindings }>()
async function admin(c: { env: Bindings; req: { header(name: string): string | undefined } }) { const auth = await authenticated(c); return auth?.user.role === 'ADMIN' && !auth.user.mustChangePassword ? auth : null }
async function accessToken(raw: string) { const service = JSON.parse(raw) as { client_email?: string; private_key?: string; token_uri?: string }; if (!service.client_email || !service.private_key || !service.token_uri) throw new Error('GOOGLE_SERVICE_ACCOUNT is missing client_email, private_key, or token_uri'); const key = await importPKCS8(service.private_key, 'RS256'); const assertion = await new SignJWT({ scope: 'https://www.googleapis.com/auth/spreadsheets' }).setProtectedHeader({ alg: 'RS256', typ: 'JWT' }).setIssuer(service.client_email).setAudience(service.token_uri).setIssuedAt().setExpirationTime('1h').sign(key); const response = await fetch(service.token_uri, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer', assertion }) }); const data = await response.json().catch(() => ({})) as { access_token?: string }; if (!response.ok || !data.access_token) throw new Error('Google token exchange failed'); return data.access_token }
const audit = (db: ReturnType<typeof getDb>, action: string, result: Result, actorId: string | null) => db.insert(schema.auditLogs).values({ id: crypto.randomUUID(), actorId, action, targetType: 'WEEKLY_SHEET', targetId: result.tabName, metadata: JSON.stringify(result), createdAt: Date.now() })

export async function runWeeklyExport(db: ReturnType<typeof getDb>, env: Pick<Bindings, 'GOOGLE_SERVICE_ACCOUNT'>, now = Date.now(), actorId: string | null = null): Promise<Result> {
  const weekMonday = mondayIst(now); const settings = (await db.select().from(schema.systemSettings).limit(1))[0]
  if (!settings?.sheetsSpreadsheetId || !env.GOOGLE_SERVICE_ACCOUNT) { const result: Result = { status: 'skipped', weekMonday, tabName: null, reason: !settings?.sheetsSpreadsheetId ? 'spreadsheet not configured' : 'GOOGLE_SERVICE_ACCOUNT not configured' }; await audit(db, 'SHEETS_JOB_SKIPPED', result, actorId).catch(() => undefined); return result }
  let tab: string | null = null
  try { const token = await accessToken(env.GOOGLE_SERVICE_ACCOUNT); const grid = await weeklyGrid(db, weekMonday); tab = tabName(weekMonday, settings.sheetsSheetName); const base = `https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(settings.sheetsSpreadsheetId)}`; const headers = { authorization: `Bearer ${token}`, 'content-type': 'application/json' }; const meta = await fetch(`${base}?fields=sheets.properties.title`, { headers }); if (!meta.ok) throw new Error(`Unable to read spreadsheet: ${await meta.text()}`); const titles = (await meta.json() as { sheets?: { properties?: { title?: string } }[] }).sheets?.map(sheet => sheet.properties?.title) ?? []; if (!titles.includes(tab)) { const add = await fetch(`${base}:batchUpdate`, { method: 'POST', headers, body: JSON.stringify({ requests: [{ addSheet: { properties: { title: tab } } }] }) }); if (!add.ok) throw new Error(`Unable to create sheet tab: ${await add.text()}`) } const range = `'${tab.replace(/'/g, "''")}'!A:ZZ`; const clear = await fetch(`${base}/values/${encodeURIComponent(range)}:clear`, { method: 'POST', headers, body: '{}' }); if (!clear.ok) throw new Error(`Unable to clear sheet tab: ${await clear.text()}`); const writeRange = `'${tab.replace(/'/g, "''")}'!A1`; const write = await fetch(`${base}/values/${encodeURIComponent(writeRange)}?valueInputOption=RAW`, { method: 'PUT', headers, body: JSON.stringify({ majorDimension: 'ROWS', values: [grid.header, ...grid.rows] }) }); if (!write.ok) throw new Error(`Unable to write sheet: ${await write.text()}`); const result: Result = { status: 'ok', weekMonday, tabName: tab, rows: grid.rows.length, cols: grid.header.length }; await audit(db, 'SHEETS_JOB_OK', result, actorId); return result } catch (error) { const result: Result = { status: 'failed', weekMonday, tabName: tab, error: error instanceof Error ? error.message : 'Unknown error' }; await audit(db, 'SHEETS_JOB_FAILED', result, actorId).catch(() => undefined); return result }
}

sheetsRoutes.post('/sheets/weekly', async c => { const auth = await admin(c); if (!auth) return c.json({ error: 'Forbidden' }, 403); const body = await c.req.json().catch(() => ({})) as { date?: unknown }; const requested = typeof body.date === 'string' ? Date.parse(body.date) : Number.NaN; if (body.date !== undefined && !Number.isFinite(requested)) return c.json({ message: 'Invalid date' }, 400); return c.json(await runWeeklyExport(getDb(c.env.DB), c.env, Number.isFinite(requested) ? requested : Date.now(), auth.user.id)) })
export { sheetsRoutes }
