import { SignJWT, importPKCS8 } from 'jose'
import { Hono } from 'hono'
import { getDb, schema } from '../db/client.js'
import { authenticated } from './auth.js'
import { mondayIst, tabName, weeklyGrid } from '../sheets/grid.js'

type Bindings = { DB: D1Database; JWT_SECRET?: string; GOOGLE_SERVICE_ACCOUNT?: string }
const sheetsRoutes = new Hono<{ Bindings: Bindings }>()
async function admin(c: { env: Bindings; req: { header(name: string): string | undefined } }) { const auth = await authenticated(c); return auth?.user.role === 'ADMIN' && !auth.user.mustChangePassword ? auth : null }
async function accessToken(raw: string) { const service = JSON.parse(raw) as { client_email: string; private_key: string; token_uri: string }; const key = await importPKCS8(service.private_key, 'RS256'); const assertion = await new SignJWT({ scope: 'https://www.googleapis.com/auth/spreadsheets' }).setProtectedHeader({ alg: 'RS256', typ: 'JWT' }).setIssuer(service.client_email).setAudience(service.token_uri).setIssuedAt().setExpirationTime('1h').sign(key); const response = await fetch(service.token_uri, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer', assertion }) }); const data = await response.json() as { access_token?: string }; if (!response.ok || !data.access_token) throw new Error('Google token exchange failed'); return data.access_token }
sheetsRoutes.post('/sheets/weekly', async c => { const auth = await admin(c); if (!auth) return c.json({ error: 'Forbidden' }, 403); const db = getDb(c.env.DB); const settings = (await db.select().from(schema.systemSettings).limit(1))[0]; const monday = mondayIst(); if (!settings?.sheetsSpreadsheetId || !c.env.GOOGLE_SERVICE_ACCOUNT) return c.json({ status: 'skipped', weekMonday: monday, tabName: null, reason: 'spreadsheet or service account not configured' }); try { const token = await accessToken(c.env.GOOGLE_SERVICE_ACCOUNT); const grid = await weeklyGrid(db, monday); const tab = tabName(monday, settings.sheetsSheetName); const base = `https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(settings.sheetsSpreadsheetId)}`; const meta = await fetch(`${base}?fields=sheets.properties.title`, { headers: { authorization: `Bearer ${token}` } }); const titles = (await meta.json() as { sheets?: { properties?: { title?: string } }[] }).sheets?.map(item => item.properties?.title) ?? []; if (!titles.includes(tab)) await fetch(`${base}:batchUpdate`, { method: 'POST', headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' }, body: JSON.stringify({ requests: [{ addSheet: { properties: { title: tab } } }] }) }); const range = `'${tab.replace(/'/g, "''")}'!A1`; const write = await fetch(`${base}/values/${encodeURIComponent(range)}?valueInputOption=RAW`, { method: 'PUT', headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' }, body: JSON.stringify({ majorDimension: 'ROWS', values: [grid.header, ...grid.rows] }) }); if (!write.ok) throw new Error(await write.text()); await db.insert(schema.auditLogs).values({ id: crypto.randomUUID(), actorId: auth.user.id, action: 'SHEETS_JOB_OK', targetType: 'WEEKLY_SHEET', targetId: tab, metadata: JSON.stringify({ weekMonday: monday }), createdAt: Date.now() }); return c.json({ status: 'ok', weekMonday: monday, tabName: tab, rows: grid.rows.length, cols: grid.header.length }) } catch (error) { return c.json({ status: 'failed', weekMonday: monday, tabName: null, error: error instanceof Error ? error.message : 'Unknown error' }, 500) } })
export { sheetsRoutes }
